Finished product catalog with cart management and orders
CristhianRodriguezMolina/phoenix-elixir pull request #17
Opened 2021-12-07 19:41 UTC by CristhianRodriguezMolina

Implemented:
* Catalog of products with categories.
* Cart for products
* Orders for payment simulation

2021-12-08 17:20 UTC, luishurtado requested changes

2021-12-08 17:20 UTC, luishurtado commented on hello/lib/hello_web/templates/order/show.html.heex
> +<span><%= link "Back", to: Routes.cart_path(@conn, :show) %></span>
👀

2021-12-08 19:06 UTC, CristhianRodriguezMolina commented on hello/lib/hello_web/templates/order/show.html.heex
> +<span><%= link "Back", to: Routes.cart_path(@conn, :show) %></span>
Fixed :+1:

2021-12-09 14:16 UTC, luishurtado approved these changes

2021-12-10 13:11 UTC, merged