Finished testing in phoenix training
CristhianRodriguezMolina/phoenix-elixir pull request #19
Opened 2021-12-08 16:20 UTC by CristhianRodriguezMolina

- Fixed tests in phoenix training
- Excluded test that are not able to fix, like tests that point to a non existent route, tests that need some authentication measures, etc.

2021-12-08 17:39 UTC, luishurtado requested changes

2021-12-08 17:39 UTC, luishurtado commented on hello/lib/hello_web/templates/page/index.html.heex
> +<h6><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h6>
👀

2021-12-08 19:08 UTC, CristhianRodriguezMolina commented on hello/lib/hello_web/templates/page/index.html.heex
> +<h6><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h6>
Fixed :+1:

2021-12-09 14:22 UTC, luishurtado approved these changes

2021-12-10 12:59 UTC, merged